### ISSUE TITLE
pt学校签到失败

### ISSUE THREAD

**Issue by lllAlex2333** [lhllhx/PT_signin#1]
1: btschool 2021-03-08 Reason: Details=> detail: join_date not found.

查看log日志有以上报错，检查cookie没问题。

**Comment by lhllhx** [comment]
我这里是正常的 发一下完整的log和配置文件 注意隐藏真实信息

**Comment by pengkaiwei** [comment]
应该是cf墙的问题吧

**Comment by lhllhx** [comment]
> 应该是cf墙的问题吧

cf墙程序会处理的 不排除处理失败的情况 但是在我这里是正常的
