### ISSUE TITLE
请求馒头时, 出现503问题

### ISSUE THREAD

**Issue by badpinkman** [lhllhx/PT_signin#13]
请求馒头时, 出现503问题.
1: m-team 2022-07-06 Reason: Sign_in=> response.status_code=503
这个问题存在约一周左右了, 希望大佬能关注一下这个问题, 如果该问题已知, 那么请忽略这个Issue.

**Comment by zzzqu** [comment]
同有这个问题，一周左右，之前正常

**Comment by lhllhx** [comment]
https://github.com/madwind/flexget_qbittorrent_mod/issues/107
