### ISSUE TITLE
定时任务执行失败

### ISSUE THREAD

**Issue by badpinkman** [lhllhx/PT_signin#14]
如题:
在执行rezip的时候出现如下异常,
==============================================
0s
Run cd $GITHUB_WORKSPACE
cp: cannot stat '/home/runner/.flexget/*.log': No such file or directory
Error: Process completed with exit code 1.
==============================================
希望大佬帮忙看下

**Comment by lhllhx** [comment]
flexget版本问题 自己PR更新一下或者重新fork一下吧

**Comment by badpinkman** [comment]
感谢
