### ISSUE TITLE
不是很理解为啥要zip

### ISSUE THREAD

**Issue by lyj0309** [lhllhx/PT_signin#17]
私人仓库也是不可见的，干嘛还需要再用密码加密一遍zip呢

**Comment by lhllhx** [comment]
当时设想防止因误操作或者github账号泄露而导致泄密 
后来阿里云版本因python加密过于麻烦而放弃加密了
沿用zip的原因是压缩省流量

**Comment by lyj0309** [comment]
确实哈，我感觉用zip的话就不能在储存库里直接看log了，还得下下来解压

**Comment by vivodi** [comment]
> 当时设想防止因误操作或者github账号泄露而导致泄密 后来阿里云版本因python加密过于麻烦而放弃加密了 沿用zip的原因是压缩省流量

目前阿里云每月提供200GB免费流量，不需要考虑流量费用问题。
https://help.aliyun.com/zh/cdt/product-overview/internet-data-transfers
