### ISSUE TITLE
为 index.py 添加异常捕获

### ISSUE THREAD

**Issue by eastarpen** [lhllhx/PT_signin#18]
第一次测试忘记去除 `config.zip` 密码

第二次测试时 [this line](https://github.com/lhllhx/PT_signin/blob/ef60e00efe9d1d73a7c99efc8d87c2f01be7399a/index.py#L12) 报错 "File  existed"

应该是上一实例未销毁造成的

建议在源码中加入判断文件是否存在或直接

```python
  try:
        os.chdir('/tmp')
        os.mkdir("/tmp/pass")
    except:
        pass
```

之后一切正常

**Comment by lhllhx** [comment]
已修复

**Comment by vivodi** [comment]
若短时间内多次使用函数，阿里云会重复使用之前的实例。

本项目程序是否妥善处理相关文件的意义不大，因为 FlexGet 并不支持在同一 Python 程序中多次调用入口：
```py
flexget.main(['execute'])
...
flexget.main(['execute'])
```

如果想短时间内多次使用函数，可以点击 “部署代码” 按钮，这样会创建新实例。
