### ISSUE TITLE
提示：OSError: invalid ppem value，无法生成report以及发送消息

### ISSUE THREAD

**Issue by JohnsonLiu1988** [lhllhx/PT_signin#21]
为防止浪费你我时间 在添加issue前 请确保已阅读以下内容

1.运行有误时，请重新阅读项目readme并检查配置流程是否完整
答：已经重新核对了一遍，流程是完整且一致的
2.提交issues时，请详细表达你遇到的问题 比如不能签到 已经签到，但不能发送消息等。并提交你的配置文件和压缩包里的log文件中
答：可以签到成功，但是无法生成report以及发送消息。提示：OSError: invalid ppem value，日志中的隐私信息已经去掉了，完整的日志已经上传。

[flexget.log](https://github.com/lhllhx/PT_signin/files/12210726/flexget.log)

**Comment by lhllhx** [comment]
疑似pillow版本问题，已回退到旧版本，请从安装依赖那一步重新部署

**Comment by JohnsonLiu1988** [comment]
感谢support，可以工作了。
