### ISSUE TITLE
怎么改自动签到的时间？

### ISSUE THREAD

**Issue by kbnq** [lhllhx/PT_signin#6]
U2早上6点还没有重置签到，想改到10点

**Comment by xu8117** [comment]
我找了下也没找到。再问个问题,cookies该怎么填写，

**Comment by xu8117** [comment]
![image](https://user-images.githubusercontent.com/39123862/128483833-6c68ed45-e6d0-42a9-b7c4-6170d9b4b6ef.png)
如图


顺便再问个问题,cookies该怎么填写，

**Comment by kbnq** [comment]
> ![图像](https://user-images.githubusercontent.com/39123862/128483833-6c68ed45-e6d0-42a9-b7c4-6170d9b4b6ef.png)
> 的
> 
> 再多问一个问题，饼干蛋糕出现，

![F12获取cookie教程](https://user-images.githubusercontent.com/22976092/128495368-a3c21cb1-c618-4fa6-a7ae-4b140fece90a.png)
上午10点的话应该怎么写？
22改成02即可
另外 因为u2签到要答题 所以u2签到不一定成功
