### ISSUE TITLE
卡Unzip了

### ISSUE THREAD

**Issue by wubushanyan** [lhllhx/PT_signin#8]
> **手动执行action后看到红的错误，进去看是unzip那一步报错了、**

![image](https://user-images.githubusercontent.com/56383722/145030480-4d3623e8-4873-422d-8615-a0e1e73e9296.png)

> **看了眼其他事项和常见问题有看到unzip的修复但是我这里还是卡住了**
> **我用的bandzip 压缩参数如下**

![image](https://user-images.githubusercontent.com/56383722/145030861-ec1b2e08-976c-4d42-bbef-d72686432a11.png)

**Comment by lhllhx** [comment]
我看到你的好像是用的旧版本 请更新或者重新fork

**Comment by wubushanyan** [comment]
搞定了 感谢
